# Etap 2 — Przetwarzanie danych

1. wczytujemy zbiór z 10% sztucznie wstrzykniętymi brakami (output Etapu 1),
2. wykonujemy **3 metody imputacji prostej** (mode, const) + **1 model-based** (KNN),
3. wykonujemy **1 imputację AutoML** (H2O),
4. dodajemy nową cechę `URL_Risk_Score` (feature engineering),
5. wykonujemy **selekcję cech** na podstawie korelacji z targetem,
6. skalujemy każdy zbiór bazowy **dwiema metodami** (min-max + standaryzacja, ręcznie),
7. otrzymujemy **4 × 2 = 8 finalnych zbiorów**.

## 1. Wczytanie zbioru z brakami

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

df_missing = pd.read_csv('data/processed/phishing_missing.csv')

X_missing = df_missing.drop('Result', axis=1)
y = df_missing['Result']

print(f"Wymiary zbioru z brakami: {df_missing.shape}")
print(f"Liczba brakow na 5 pierwszych kolumnach:")
print(X_missing.isnull().sum().head(5))
print(f"\nLaczna liczba brakow: {X_missing.isnull().sum().sum()}")
print(f"Procent brakow: {X_missing.isnull().sum().sum() / X_missing.size * 100:.2f}%")

Wymiary zbioru z brakami: (11055, 31)
Liczba brakow na 5 pierwszych kolumnach:
having_IP_Address           1105
URL_Length                  1105
Shortining_Service          1105
having_At_Symbol            1105
double_slash_redirecting    1105
dtype: int64

Laczna liczba brakow: 33150
Procent brakow: 10.00%

## 2. Imputacja braków — 3 sposoby

In [13]:
from sklearn.impute import SimpleImputer, KNNImputer

# Most Frequent (moda)
imputer_mode = SimpleImputer(strategy='most_frequent')
X_imputed_mode = pd.DataFrame(
    imputer_mode.fit_transform(X_missing),
    columns=X_missing.columns
).astype(int)

# Constant (stala 0)
imputer_constant = SimpleImputer(strategy='constant', fill_value=0)
X_imputed_const = pd.DataFrame(
    imputer_constant.fit_transform(X_missing),
    columns=X_missing.columns
).astype(int)

# KNN (k=5) - model-based
imputer_knn = KNNImputer(n_neighbors=5)
X_imputed_knn_raw = imputer_knn.fit_transform(X_missing)
X_imputed_knn = pd.DataFrame(
    np.round(X_imputed_knn_raw),
    columns=X_missing.columns
).astype(int)

y = y.astype(int)

df_mode = pd.concat([X_imputed_mode, y], axis=1)
df_const = pd.concat([X_imputed_const, y], axis=1)
df_knn = pd.concat([X_imputed_knn, y], axis=1)

print("Imputacja zakonczona. Sprawdzenie brakow:")
for name, d in [("mode", df_mode), ("const", df_const), ("knn", df_knn)]:
    n_na = d.isnull().sum().sum()
    print(f"  {name:6s}: {n_na} brakow, shape {d.shape}")

Imputacja zakonczona. Sprawdzenie brakow:
  mode  : 0 brakow, shape (11055, 31)
  const : 0 brakow, shape (11055, 31)
  knn   : 0 brakow, shape (11055, 31)

## 3. Analiza wartości odstających

In [14]:
def check_value_range(name, df):
    bad = ~df.drop("Result", axis=1).isin([-1, 0, 1])
    n_bad = bad.sum().sum()
    print(f"  {name:6s}: {n_bad} wartosci poza {{-1, 0, 1}}")

print("Weryfikacja zakresow wartosci po imputacji:")
for name, d in [("mode", df_mode), ("const", df_const), ("knn", df_knn)]:
    check_value_range(name, d)

print("\nUwaga: dla danych {-1, 0, 1} klasyczne outliery (IQR, z-score) nie maja sensu.")
print("Sprawdzamy tylko, czy imputacja nie wprowadzila wartosci poza dozwolony zbior.")

Weryfikacja zakresow wartosci po imputacji:
  mode  : 0 wartosci poza {-1, 0, 1}
  const : 0 wartosci poza {-1, 0, 1}
  knn   : 0 wartosci poza {-1, 0, 1}

Uwaga: dla danych {-1, 0, 1} klasyczne outliery (IQR, z-score) nie maja sensu.
Sprawdzamy tylko, czy imputacja nie wprowadzila wartosci poza dozwolony zbior.

## 4. Imputacja AutoML (H2O)

In [15]:
import h2o

print("Uruchamianie H2O do imputacji (AutoML)...")
h2o.init(verbose=False)
hf_missing = h2o.H2OFrame(df_missing)

for col in hf_missing.columns:
    if col != 'Result':
        hf_missing.impute(col, method='mode')

df_automl = hf_missing.as_data_frame()
df_automl = df_automl[df_missing.columns]
df_automl = df_automl.astype(int)

h2o.cluster().shutdown()

base_datasets = {
    'mode': df_mode,        # Prosty 1
    'const': df_const,      # Prosty 2
    'knn': df_knn,          # Model-based
    'automl': df_automl,    # AutoML (H2O mode)
}

print("\nWygenerowano 4 zbiory bazowe:")
for name, d in base_datasets.items():
    print(f"  {name:8s} -> shape {d.shape}")

Uruchamianie H2O do imputacji (AutoML)...
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

Wygenerowano 4 zbiory bazowe:
  mode     -> shape (11055, 31)
  const    -> shape (11055, 31)
  knn      -> shape (11055, 31)
  automl   -> shape (11055, 31)

C:\Users\User\PycharmProjects\ML_Phishing_Project\.venv\Lib\site-packages\h2o\frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

## 5. Nowa cecha — URL_Risk_Score

Tworzymy nową cechę jako sumę 4 cech związanych z URL:
`URL_Length + having_At_Symbol + Prefix_Suffix + Abnormal_URL`.

In [16]:
url_features = ['URL_Length', 'having_At_Symbol', 'Prefix_Suffix', 'Abnormal_URL']

for name in base_datasets:
    base_datasets[name] = base_datasets[name].copy()
    base_datasets[name]['URL_Risk_Score'] = base_datasets[name][url_features].sum(axis=1)

korelacja = base_datasets['knn']['URL_Risk_Score'].corr(base_datasets['knn']['Result'])
print(f"Korelacja URL_Risk_Score z Result (na zbiorze knn, Pearson): {korelacja:.3f}")

print("\nPrzykladowe wartosci URL_Risk_Score (knn):")
display(base_datasets['knn'][url_features + ['URL_Risk_Score', 'Result']].head())

Korelacja URL_Risk_Score z Result (na zbiorze knn, Pearson): 0.197

Przykladowe wartosci URL_Risk_Score (knn):

,URL_Length,having_At_Symbol,Prefix_Suffix,Abnormal_URL,URL_Risk_Score,Result
0,1,1,-1,-1,0,-1
1,1,1,-1,1,2,-1
2,0,1,-1,-1,-1,-1
3,0,1,-1,1,1,-1
4,0,1,-1,1,1,1

## 6. Selekcja cech
Selekcja cech: usuwamy cechy z |Spearman r z Result| < 0.05.

In [17]:
THRESHOLD = 0.05

corr_with_target = base_datasets['knn'].corr(method='spearman')['Result'].drop('Result')
abs_corr = corr_with_target.abs().sort_values(ascending=False)

features_keep = abs_corr[abs_corr >= THRESHOLD].index.tolist()
features_drop = abs_corr[abs_corr < THRESHOLD].index.tolist()

print(f"Prog |r| >= {THRESHOLD}")
print(f"Cech zachowanych: {len(features_keep)}")
print(f"Cech usunietych:  {len(features_drop)}")
print(f"\nUsuniete cechy (posortowane wg |r|):")
for f in features_drop:
    print(f"  {f:<32}  r = {corr_with_target[f]:+.3f}")

print(f"\nTop 5 zachowanych cech wg |r|:")
for f in features_keep[:5]:
    print(f"  {f:<32}  r = {corr_with_target[f]:+.3f}")

columns_keep = features_keep + ['Result']
for name in base_datasets:
    base_datasets[name] = base_datasets[name][columns_keep]

print(f"\nWymiary po selekcji cech:")
for name, d in base_datasets.items():
    print(f"  {name:8s} -> shape {d.shape}")

Prog |r| >= 0.05
Cech zachowanych: 20
Cech usunietych:  11

Usuniete cechy (posortowane wg |r|):
  on_mouseover                      r = +0.043
  HTTPS_token                       r = -0.043
  double_slash_redirecting          r = -0.042
  Links_pointing_to_page            r = +0.041
  port                              r = +0.037
  Submitting_to_email               r = +0.016
  Redirect                          r = -0.012
  RightClick                        r = +0.011
  Iframe                            r = -0.003
  Favicon                           r = -0.000
  popUpWidnow                       r = -0.000

Top 5 zachowanych cech wg |r|:
  SSLfinal_State                    r = +0.732
  URL_of_Anchor                     r = +0.695
  web_traffic                       r = +0.368
  Prefix_Suffix                     r = +0.354
  having_Sub_Domain                 r = +0.310

Wymiary po selekcji cech:
  mode     -> shape (11055, 21)
  const    -> shape (11055, 21)
  knn      -> shape (11055, 21)
  automl   -> shape (11055, 21)

## 7. Skalowanie cech (min-max + standaryzacja, ręcznie)

In [18]:
def min_max_scaler_manual(df, target_col='Result'):
    """Skalowanie min-max do [0, 1]. Implementacja od zera, bez sklearn."""
    df_scaled = df.copy()
    features = [c for c in df.columns if c != target_col]
    for col in features:
        min_val = df_scaled[col].min()
        max_val = df_scaled[col].max()
        if max_val != min_val:
            df_scaled[col] = (df_scaled[col] - min_val) / (max_val - min_val)
    return df_scaled


def standardization_manual(df, target_col='Result'):
    """Standaryzacja (z-score). Implementacja od zera."""
    df_scaled = df.copy()
    features = [c for c in df.columns if c != target_col]
    for col in features:
        mean_val = df_scaled[col].mean()
        std_val = df_scaled[col].std()
        if std_val != 0:
            df_scaled[col] = (df_scaled[col] - mean_val) / std_val
    return df_scaled


final_datasets = {}
for name, dataset in base_datasets.items():
    final_datasets[f"{name}_minmax"] = min_max_scaler_manual(dataset)
    final_datasets[f"{name}_std"] = standardization_manual(dataset)

print(f"Wygenerowano {len(final_datasets)} przeskalowanych zbiorow:")
for name in final_datasets:
    print(f"  - {name}")

print("\nPrzyklad pierwszych wierszy 'knn_std':")
display(final_datasets['knn_std'].head())

print("\nStatystyki dla 'knn_std':")
display(final_datasets['knn_std'].describe().T[['mean', 'std']].head())

Wygenerowano 8 przeskalowanych zbiorow:
  - mode_minmax
  - mode_std
  - const_minmax
  - const_std
  - knn_minmax
  - knn_std
  - automl_minmax
  - automl_std

Przyklad pierwszych wierszy 'knn_std':

,SSLfinal_State,URL_of_Anchor,web_traffic,Prefix_Suffix,having_Sub_Domain,Request_URL,Links_in_tags,Domain_registeration_length,SFH,URL_Risk_Score,...,Google_Index,Page_Rank,having_IP_Address,Statistical_report,DNSRecord,Shortining_Service,Abnormal_URL,URL_Length,having_At_Symbol,Result
0,-1.396232,-1.304852,-1.594559,-0.395219,-1.327768,0.837665,1.500003,-0.717358,-0.537105,-0.029002,...,0.399632,-0.592863,-1.413986,-2.541973,-1.506455,0.386980,-2.436393,2.17853,0.416613,-1
1,0.833020,0.109377,-0.359856,-0.395219,-0.077259,0.837665,-1.176109,-0.717358,-0.537105,1.405505,...,0.399632,-0.592863,0.723525,0.399054,-1.506455,0.386980,0.414252,2.17853,0.416613,-1
2,-1.396232,0.109377,0.874847,-0.395219,-1.327768,0.837665,-1.176109,-0.717358,-0.537105,-0.746255,...,0.399632,-0.592863,0.723525,-2.541973,-1.506455,0.386980,-2.436393,0.85051,0.416613,-1
3,-1.396232,0.109377,-0.359856,-0.395219,-1.327768,-1.231002,0.161947,1.437347,-0.537105,0.688252,...,0.399632,-0.592863,0.723525,0.399054,-1.506455,0.386980,0.414252,0.85051,0.416613,-1
4,0.833020,0.109377,-0.359856,-0.395219,1.173250,0.837665,0.161947,-0.717358,-0.537105,0.688252,...,0.399632,-0.592863,0.723525,0.399054,-1.506455,-2.592175,0.414252,0.85051,0.416613,1

Statystyki dla 'knn_std' (powinno byc srednia ~0, std ~1 dla cech):

                           mean  std
SSLfinal_State     3.406492e-17  1.0
URL_of_Anchor     -3.599312e-17  1.0
web_traffic        6.105976e-17  1.0
Prefix_Suffix     -3.856406e-17  1.0
having_Sub_Domain  0.000000e+00  1.0

## 8. Zapis 8 finalnych zbiorów

In [19]:
os.makedirs('data/processed/final_datasets', exist_ok=True)

for name, dataset in final_datasets.items():
    file_path = f"data/processed/final_datasets/{name}.csv"
    dataset.to_csv(file_path, index=False)

print(f"Zapisano {len(final_datasets)} plikow do data/processed/final_datasets/")
print("Lista plikow:")
for name in final_datasets:
    print(f"  - {name}.csv ({final_datasets[name].shape[0]} wierszy x {final_datasets[name].shape[1]} kolumn)")

Zapisano 8 plikow do data/processed/final_datasets/
Lista plikow:
  - mode_minmax.csv (11055 wierszy x 21 kolumn)
  - mode_std.csv (11055 wierszy x 21 kolumn)
  - const_minmax.csv (11055 wierszy x 21 kolumn)
  - const_std.csv (11055 wierszy x 21 kolumn)
  - knn_minmax.csv (11055 wierszy x 21 kolumn)
  - knn_std.csv (11055 wierszy x 21 kolumn)
  - automl_minmax.csv (11055 wierszy x 21 kolumn)
  - automl_std.csv (11055 wierszy x 21 kolumn)